import { Platform } from 'react-native';
import { PlatformEnum } from '../utils/constants';

export abstract class Fonts {

    public static FordAntennaCompWGLBlack: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaCompWGL-Black' : 'FordAntennaComp-Black';
    public static FordAntennaCompWGLBoldItalic: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaCompWGL-BoldItalic' : 'FordAntennaComp-BoldItalic';
    public static FordAntennaCompWGLExtLight: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaCompWGL-ExtLight' : 'FordAntennaComp-ExtLight';
    public static FordAntennaCompWGLBlackItalic: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaCompWGL-BlackItalic' : 'FordAntennaComp-BlackItalic';
    public static FordAntennaCompWGLExtLigIt: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaCompWGL-ExtLigIt' : 'FordAntennaComp-ExtLigIt';
    public static FordAntennaCompWGLBold: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaCompWGL-Bold' : 'FordAntennaComp-Bold';
    public static FordAntennaCompWGLLight: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaCompWGL-Light' : 'FordAntennaCompWGL-Light';
    public static FordAntennaCompWGLLightIta: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaCompWGL-LightIta' : 'FordAntennaComp-LightIta';
    public static FordAntennaCompWGLMed: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaCompWGL-Med' : 'FordAntennaComp-Med';
    public static FordAntennaCompWGLMedItalic: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaCompWGL-MedItalic' : 'FordAntennaComp-MedItalic';
    public static FordAntennaCompWGLReg: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaCompWGL-Reg' : 'FordAntennaComp-Reg';
    public static FordAntennaCompWGLRegItalic: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaCompWGL-RegItalic' : 'FordAntennaComp-RegItalic';
    public static FordAntennaCompWGLSemibold: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaCompWGL-Semibold' : 'FordAntennaComp-Semibold';
    public static FordAntennaCompWGLSemiboldIta: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaCompWGL-SemiboldIta' : 'FordAntennaComp-SemiboldIta' ;
    public static FordAntennaCompWGLThin: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaCompWGL-Thin' : 'FordAntennaComp-Thin';
    public static FordAntennaCompWGLThinItalic: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaCompWGL-ThinItalic' : 'FordAntennaComp-ThinItalic';
    public static FordAntennaCondWGLBlack: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaCondWGL-Black' : 'FordAntennaCond-Black';
    public static FordAntennaCondWGLBlackItalic: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaCondWGL-BlackItalic' : 'FordAntennaCond-BlackItalic';
    public static FordAntennaCondWGLBold: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaCondWGL-Bold' : 'FordAntennaCond-Bold';
    public static FordAntennaCondWGLBoldItalic: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaCondWGL-BoldItalic' : 'FordAntennaCond-BoldItalic';
    public static FordAntennaCondWGLExtLightIta: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaCondWGL-ExtLightIta' : 'FordAntennaCond-ExtLightIta';
    public static FordAntennaCondWGLExtraLight: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaCondWGL-ExtraLight' : 'FordAntennaCond-ExtraLight';
    public static FordAntennaCondWGLLight: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaCondWGL-Light' : 'FordAntennaCond-Light';
    public static FordAntennaCondWGLLightItalic: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaCondWGL-LightItalic' : 'FordAntennaCond-LightItalic';
    public static FordAntennaCondWGLMed: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaCondWGL-Med' : 'FordAntennaCond-Med';
    public static FordAntennaCondWGLMedItalic: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaCondWGL-MedItalic' : 'FordAntennaCond-MedItalic' ;
    public static FordAntennaCondWGLReg: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaCondWGL-Reg' : 'FordAntennaCond-Reg' ;
    public static FordAntennaCondWGLRegItalic: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaCondWGL-RegItalic' : 'FordAntennaCond-RegItalic';
    public static FordAntennaCondWGLThin: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaCondWGL-Thin' : 'FordAntennaCond-Thin';
    public static FordAntennaCondWGLThinItalic: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaCondWGL-ThinItalic' : 'FordAntennaCond-ThinItalic' ;
    public static FordAntennaExtraCondWGLBlack: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaExtraCondWGL-Black' : 'FordAntennaExtraCond-Black';
    public static FordAntennaExtraCondWGLBlackIt: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaExtraCondWGL-BlackIt' : 'FordAntennaExtraCond-BlackIt';
    public static FordAntennaExtraCondWGLBold: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaExtraCondWGL-Bold' : 'FordAntennaExtraCond-Bold';
    public static FordAntennaExtraCondWGLBoldIt: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaExtraCondWGL-BoldIt' : 'FordAntennaExtraCond-BoldIt';
    public static FordAntennaExtraCondWGLExtLig: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaExtraCondWGL-ExtLig' : 'FordAntennaExtraCond-ExtLig';
    public static FordAntennaExtraCondWGLExtLigIt: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaExtraCondWGL-ExtLigIt' : 'FordAntennaExtraCond-ExtLigIt';
    public static FordAntennaExtraCondWGLLight: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaExtraCondWGL-Light' : 'FordAntennaExtraCond-Light';
    public static FordAntennaExtraCondWGLLigIt: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaExtraCondWGL-LigIt' : 'FordAntennaExtraCond-LigIt';
    public static FordAntennaExtraCondWGLMed: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaExtraCondWGL-Med' : 'FordAntennaExtraCond-Med';
    public static FordAntennaExtraCondWGLMedIt: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaExtraCondWGL-MedIt' : 'FordAntennaExtraCond-MedIt';
    public static FordAntennaExtraCondWGLReg: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaExtraCondWGL-Reg' : 'FordAntennaExtraCond-Reg';
    public static FordAntennaExtraCondWGLRegIta: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaExtraCondWGL-RegIta' : 'FordAntennaExtraCond-RegIta';
    public static FordAntennaExtraCondWGLSemibold: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaExtraCondWGL-Semibold' : 'FordAntennaExtraCond-Semibold';
    public static FordAntennaExtraCondWGLSemiboldIta: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaExtraCondWGL-SemiboldIta' : 'FordAntennaExtraCond-SemiboldIta' ;
    public static FordAntennaExtraCondWGLThin: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaExtraCondWGL-Thin' : 'FordAntennaExtraCond-Thin';
    public static FordAntennaExtraCondWGLThinIta: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaExtraCondWGL-ThinIta' : 'FordAntennaExtraCond-ThinIta';
    public static FordAntennaWGLBlack: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaWGL-Black' : 'FordAntenna-Black';
    public static FordAntennaWGLBlackItalic: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaWGL-BlackItalic' : 'FordAntenna-BlackItalic';
    public static FordAntennaWGLBold: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaWGL-Bold' : 'FordAntenna-Bold';
    public static FordAntennaWGLBoldItalic: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaWGL-BoldItalic' : 'FordAntenna-BoldItalic';
    public static FordAntennaWGLExtraLight: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaWGL-ExtraLight' : 'FordAntenna-ExtraLight';
    public static FordAntennaWGLExtraLightItalic: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaWGL-ExtraLightItalic' : 'FordAntenna-ExtraLightItalic';
    public static FordAntennaWGLLight: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaWGL-Light' : 'FordAntenna-Light';
    public static FordAntennaWGLLightItalic: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaWGL-LightItalic' : 'FordAntenna-LightItalic';
    public static FordAntennaWGLMedium: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaWGL-Medium' : 'FordAntenna-Medium';
    public static FordAntennaWGLMediumItalic: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaWGL-MediumItalic' : 'FordAntenna-MediumItalic';
    public static FordAntennaWGLRegular: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaWGL-Regular' : 'FordAntenna-Regular';
    public static FordAntennaWGLRegularItalic: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaWGL-RegularItalic' : 'FordAntenna-RegularItalic';
    public static FordAntennaWGLSemibold: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaWGL-Semibold' : 'FordAntenna-Semibold';
    public static FordAntennaWGLSemiboldItalic: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaWGL-SemiboldItalic' : 'FordAntenna-SemiboldItalic';
    public static FordAntennaWGLThin: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaWGL-Thin' : 'FordAntenna-Thin';
    public static FordAntennaWGLThinItalic: string = Platform.OS === PlatformEnum.ANDROID ? 'FordAntennaWGL-ThinItalic' : 'FordAntenna-ThinItalic';

}