export enum Screens {
    SyncNotFound = 'SyncNotFound',
    NavDrawer = 'NavDrawer',
    Events = 'Events',
    SubEvents = 'SubEvents',
    Guests = 'Guests',
    QRCodeGuestScanner = 'QRCodeGuestScanner',
    QRTestDriveScanner = 'QRTestDriveScanner',
    Home = 'Home',
    Vehicles = 'Vehicles',
    VehicleNavigator = 'VehicleNavigator',
    VehicleDetail = 'VehicleDetail',
    VehicleComparator = 'VehicleComparator',
    NewsletterForm = 'NewsletterForm',
    NewsletterFormStack = 'NewsletterFormStack',
    DealerShips = 'DealerShips',
    DelaerShipQuoteForm = 'DelaerShipQuoteForm',
    TestDriveForm = 'TestDriveForm',
    TestDriveFormStack = 'TestDriveFormStack',
    TestDriveSignature = 'TestDriveSignature',
    CampaignsChecker = 'CampaignsChecker',
    SearchHistory = 'SearchHistory',
    ContactInformation = 'ContactInformation',
    SyncForms = 'SyncForms',
    SyncGuests = 'SyncGuests',
    SyncDevices = 'SyncDevices'
}